Pass RN Events and screen views
applicaster-plugins/EasyTracking-Android pull request #8
Opened 2020-09-30 12:37 UTC by meravz82

[IM-932](https://applicaster.atlassian.net/secure/RapidBoard.jspa?rapidView=232&projectKey=IM&modal=detail&selectedIssue=IM-932&assignee=557058%3Af340762e-81f8-4786-9299-551ed2f40a34): Pass R.N Events to EasyTracking

2020-09-30 13:10 UTC, drazumeev-sc commented on plugin/src/main/java/com/applicaster/easytracking/EasyTrackingAnalyticsAgent.kt
> +        LocalBroadcastManager.getInstance(context!!).registerReceiver(object : BroadcastReceiver() {
It will be better to avoid unsafe unwrap for nullable fields, i.e. `!!`
Please add if `(context != null)` check or use scope function like `context?.let{...}`

2020-09-30 13:15 UTC, drazumeev-sc commented on plugin/src/main/java/com/applicaster/easytracking/EasyTrackingAnalyticsAgent.kt
> +                        val isScreenView = event_properties.get("screenView") as Boolean
If data structure will be changed in future this code will return unhandled `null `object
Please use safe cast operator `as?` and` Boolean?` with corresponding checks

2020-09-30 13:18 UTC, drazumeev-sc requested changes
@meravz82 Looks good, but it'll be better to add some additional checks for potentially `nullable `objects. Please check my comments

2020-09-30 13:18 UTC, drazumeev-sc commented on plugin/src/main/java/com/applicaster/easytracking/EasyTrackingAnalyticsAgent.kt
> +                            val screenName = event_properties.get("eventName") as String
Same as for unsafe Boolean type cast. Please use `as?` and handle nullable `String?`

2020-09-30 13:24 UTC, drazumeev-sc commented on plugin/src/main/java/com/applicaster/easytracking/EasyTrackingAnalyticsAgent.kt
> +                        val isScreenView = event_properties.get("screenView") as Boolean
i.e
`  val isScreenView = event_properties.get("screenView") as? Boolean?`
For more info see: https://kotlinlang.org/docs/reference/typecasts.html#safe-nullable-cast-operator

2020-09-30 16:35 UTC, meravz82 commented on plugin/src/main/java/com/applicaster/easytracking/EasyTrackingAnalyticsAgent.kt
> +        LocalBroadcastManager.getInstance(context!!).registerReceiver(object : BroadcastReceiver() {
Done

2020-09-30 16:36 UTC, meravz82 commented on plugin/src/main/java/com/applicaster/easytracking/EasyTrackingAnalyticsAgent.kt
> +                        val isScreenView = event_properties.get("screenView") as Boolean
Done

2020-09-30 16:37 UTC, meravz82 commented on plugin/src/main/java/com/applicaster/easytracking/EasyTrackingAnalyticsAgent.kt
> +                            val screenName = event_properties.get("eventName") as String
Done

2020-10-01 07:58 UTC, drazumeev-sc approved these changes
💯

2020-10-01 08:33 UTC, merged